import { Types } from "mongoose";
import { TBloodGroup, TGender, TUserName } from "../student/student.interface";
export type TAdmin = {
    id: string;
    userId: Types.ObjectId;
    name: TUserName;
    age: number;
    gender: TGender;
    bloodGroup: TBloodGroup;
    designation: string;
    dateOfBirth: string;
    email: string;
    contactNo: string;
    emergencyContactNo: string;
    presentAddress: string;
    permanentAddress: string;
    department: string;
    profileImg: string;
    isDeleted: boolean;
};
